# Generated by Django 4.0 on 2024-11-05 13:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone
import sizefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=100)),
                ('file_size', sizefield.models.FileSizeField()),
                ('file_format', models.CharField(max_length=100)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('recording_dt', models.DateTimeField(db_index=True, null=True)),
                ('path', models.CharField(max_length=500)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('extra_versions', models.JSONField(blank=True, default=dict)),
                ('thumb_path', models.JSONField(blank=True, default=None, null=True)),
                ('local_storage', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('do_not_remove', models.BooleanField(default=False)),
                ('original_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('tag', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('deployment_device_ID', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('deployment_ID', models.CharField(max_length=50)),
                ('device_n', models.IntegerField(default=1)),
                ('deploymentStart', models.DateTimeField(default=django.utils.timezone.now)),
                ('deploymentEnd', models.DateTimeField(blank=True, null=True)),
                ('Latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('Longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('combo_project', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('last_imageURL', models.CharField(blank=True, editable=False, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('device_ID', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('autoupdate', models.BooleanField(default=False)),
                ('update_time', models.IntegerField(default=48)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('authentication', models.CharField(blank=True, max_length=100, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('project_ID', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('objectives', models.CharField(blank=True, max_length=500)),
                ('principal_investigator', models.CharField(blank=True, max_length=50)),
                ('principal_investigator_email', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('contact_email', models.CharField(blank=True, max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=100)),
                ('archive_files', models.BooleanField(default=True)),
                ('clean_time', models.IntegerField(default=90)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
