# Generated by Django 4.0 on 2024-03-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='deploymentEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
