# Generated by Django 4.0 on 2024-11-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_rename_deploymentend_deployment_deployment_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
