# Generated by Django 4.0 on 2024-03-12 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_alter_deployment_deploymentend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='do_not_delete',
            new_name='do_not_remove',
        ),
        migrations.AlterField(
            model_name='deployment',
            name='last_file',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_last_file', to='data_models.datafile'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='last_image',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployment_last_image', to='data_models.datafile'),
        ),
    ]
