# Generated by Django 4.0 on 2024-12-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0004_alter_device_type_alter_project_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='deployment',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
