# Generated by Django 4.0 on 2024-03-18 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_alter_device_authentication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='download_date',
            new_name='upload_date',
        ),
    ]
