# Generated by Django 4.0 on 2025-01-07 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_rename_latitude_deployment_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='datafile',
            name='upload_dt',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 7, 13, 47, 56, 718691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_format',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(max_length=50),
        ),
    ]
