# Generated by Django 4.0 on 2025-01-07 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0006_remove_datafile_upload_date_datafile_upload_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='upload_dt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
