# Generated by Django 4.0 on 2024-08-28 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0006_rename_download_date_datafile_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='device_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='site',
            name='short_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
