# Generated by Django 4.0 on 2025-01-14 13:38

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0007_alter_datafile_upload_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='UTC', use_pytz=True),
        ),
    ]
