# Generated by Django 4.0 on 2025-01-15 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0008_deployment_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='data_models.datatype'),
        ),
    ]
