# Generated by Django 4.2 on 2025-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0009_alter_datafile_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
