# Generated by Django 4.2 on 2025-01-23 10:28

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0011_rename_authentication_device_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DataStorageInput',
        ),
    ]
