# Generated by Django 4.2 on 2025-01-27 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('external_storage_import', '0003_rename_service_password_datastorageinput_password_and_more'),
        ('data_models', '0012_alter_device_password_delete_datastorageinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='input_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_devices', to='external_storage_import.datastorageinput'),
        ),
        migrations.AddField(
            model_name='project',
            name='data_storages',
            field=models.ManyToManyField(related_name='linked_projects', to='external_storage_import.datastorageinput'),
        ),
    ]
