# Generated by Django 4.2 on 2025-02-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0014_alter_datafile_file_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='extra_versions',
            new_name='linked_files',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='thumb_path',
        ),
        migrations.AddField(
            model_name='datafile',
            name='thumb_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
