# Generated by Django 4.2 on 2025-02-10 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0001_initial'),
        ('data_models', '0016_rename_last_imageurl_deployment_thumb_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archive_files',
        ),
        migrations.AddField(
            model_name='datafile',
            name='arfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='archiving.tarfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='archives',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='archiving.archive'),
        ),
    ]
