# Generated by Django 4.2 on 2025-02-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_storage_import', '0003_rename_service_password_datastorageinput_password_and_more'),
        ('data_models', '0018_rename_arfile_datafile_tar_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='archives',
            new_name='archive',
        ),
        migrations.AlterField(
            model_name='project',
            name='data_storages',
            field=models.ManyToManyField(blank=True, related_name='linked_projects', to='external_storage_import.datastorageinput'),
        ),
    ]
