# Generated by Django 4.2 on 2025-03-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0019_rename_archives_project_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='has_human',
            field=models.BooleanField(default=False),
        ),
    ]
