# Generated by Django 4.2 on 2025-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0020_datafile_has_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
