# Generated by Django 4.2 on 2025-04-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0021_alter_project_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(max_length=50)),
                ('celery_job_name', models.CharField(max_length=50)),
                ('job_args', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='automated_tasks',
            field=models.ManyToManyField(blank=True, related_name='linked_projects', to='data_models.projectjob'),
        ),
    ]
