# Generated by Django 4.2 on 2025-04-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0003_remove_tarfile_comboproject_alter_tarfile_archive'),
        ('data_models', '0022_projectjob_project_automated_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='archiving.archive'),
        ),
    ]
