# Generated by Django 4.2 on 2025-04-25 13:04

import colorfield.fields
from django.db import migrations
import django_icon_picker.field


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0023_alter_project_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatype',
            name='colour',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='datatype',
            name='symbol',
            field=django_icon_picker.field.IconField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='colour',
            field=colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='symbol',
            field=django_icon_picker.field.IconField(blank=True, max_length=255),
        ),
    ]
