# Generated by Django 4.2 on 2025-05-02 13:47

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0024_datatype_colour_datatype_symbol_devicemodel_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectjob',
            name='obj_type',
            field=models.CharField(default='datafile', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatype',
            name='colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
