# Generated by Django 4.2 on 2025-06-01 21:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0024_datatype_colour_datatype_symbol_devicemodel_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='colour',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_ID',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_device_ID',
            field=models.CharField(blank=True, editable=False, max_length=110, unique=True),
        ),
    ]
