# Generated by Django 4.2 on 2025-06-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0025_alter_datafile_file_name_alter_datatype_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
