# Generated by Django 4.2 on 2025-06-08 21:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_models', '0026_alter_datafile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='annotators',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='annotatable_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='managers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='managed_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='project',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='deployments', to='data_models.project'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='viewers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='viewable_deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='annotators',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='annotatable_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='managers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='managed_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='viewers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='viewable_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='annotators',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='annotatable_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='managed_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='viewers',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='viewable_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
