# Generated by Django 4.2 on 2025-06-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0027_alter_datafile_tag_alter_deployment_annotators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='annotators',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='managers',
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='viewers',
        ),
    ]
