# Generated by Django 4.2 on 2025-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0028_remove_deployment_annotators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='has_human',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='local_storage',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
