# Generated by Django 4.2 on 2025-06-16 19:36

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import (BtreeGinExtension,
                                                TrigramExtension)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0029_alter_datafile_has_human_and_more'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='datafile',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(
                django.db.models.functions.text.Upper('tag'), name='gin_trgm_ops'), name='upper_tag_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='datafile',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(
                django.db.models.functions.text.Upper('file_name'), name='gin_trgm_ops'), name='upper_file_name_gin_idx'),
        ),
    ]
