# Generated by Django 4.2 on 2025-06-20 08:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0030_datafile_tag_gin_idx_datafile_file_name_gin_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='archived',
            field=models.BooleanField(default=False, help_text='archived.'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_format',
            field=models.CharField(help_text='file format.', max_length=10),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_name',
            field=models.CharField(db_index=True, help_text='file name.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_size',
            field=sizefield.models.FileSizeField(help_text='file size.'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file_type',
            field=models.ForeignKey(default=None, help_text='file type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Numeric database ID of datafile of this observation.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='local_storage',
            field=models.BooleanField(db_index=True, default=True, help_text='local storage.'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='original_name',
            field=models.CharField(blank=True, help_text='original name.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='recording_dt',
            field=models.DateTimeField(db_index=True, help_text='recording dt.', null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='upload_dt',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='upload dt.'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(help_text='device type name.', max_length=20),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_device_ID',
            field=models.CharField(blank=True, editable=False, help_text='deployment device ID.', max_length=110, unique=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_end',
            field=models.DateTimeField(blank=True, help_text='deployment end.', null=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployment_start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='deployment start.'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='device',
            field=models.ForeignKey(help_text='deployment device.', on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.device'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='device_type',
            field=models.ForeignKey(help_text='device type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Numeric database ID of deployment to which                           the datafiles of this observation are attached.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='is active.'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='site',
            field=models.ForeignKey(help_text='site.', on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='data_models.site'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_ID',
            field=models.CharField(help_text='device device ID.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='device id.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, help_text='device name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(help_text='type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Unique numeric identifier of the object.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='name',
            field=models.CharField(blank=True, help_text='model name.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='type',
            field=models.ForeignKey(help_text='type.', on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='data_models.datatype'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='project id.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='organisation',
            field=models.CharField(blank=True, help_text='organisation.', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_ID',
            field=models.CharField(blank=True, help_text='project project ID.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(help_text='site name.', max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='short_name',
            field=models.CharField(blank=True, help_text='site short name.', max_length=10),
        ),
    ]
