# Generated by Django 4.2 on 2025-01-23 10:36

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('external_storage_import', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorageinput',
            old_name='username',
            new_name='service_username',
        ),
        migrations.RemoveField(
            model_name='datastorageinput',
            name='password',
        ),
        migrations.AddField(
            model_name='datastorageinput',
            name='service_password',
            field=encrypted_model_fields.fields.EncryptedCharField(default='foo'),
            preserve_default=False,
        ),
    ]
