# Generated by Django 4.2 on 2025-01-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_storage_import', '0002_rename_username_datastorageinput_service_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorageinput',
            old_name='service_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='datastorageinput',
            old_name='service_username',
            new_name='username',
        ),
    ]
