# Generated by Django 4.2 on 2025-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_storage_import', '0003_rename_service_password_datastorageinput_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorageinput',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Unique numeric identifier of the object.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
