# Generated by Django 4.2 on 2025-06-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_storage_import', '0004_alter_datastorageinput_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorageinput',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
