# Generated by Django 4.0 on 2024-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_alter_deployment_deploymentend'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='deployment',
            field=models.ManyToManyField(related_name='usergroup', to='data_models.Deployment'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='device',
            field=models.ManyToManyField(related_name='usergroup', to='data_models.Device'),
        ),
    ]
