# Generated by Django 4.2 on 2025-06-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_bio_user_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Numeric database ID of user who created this observation.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
