# Generated by Django 4.2 on 2025-06-23 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0032_deployment_annotators_deployment_managers_and_more'),
        ('user_management', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceuser',
            name='device',
            field=models.OneToOneField(help_text='Device linked to this device user.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_user', to='data_models.device'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='User self description.', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organisation',
            field=models.CharField(blank=True, help_text='User organisation.', max_length=100),
        ),
    ]
