# Generated by Django 4.0 on 2024-03-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_alter_device_authentication'),
        ('user_management', '0003_deviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuser',
            name='device',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_user', to='data_models.device'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
