# Generated by Django 4.2 on 2025-02-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archiving', '0002_alter_tarfile_archived_dt_alter_tarfile_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarfile',
            name='comboproject',
        ),
        migrations.AlterField(
            model_name='tarfile',
            name='archive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tar_files', to='archiving.archive'),
        ),
    ]
