# Generated by Django 4.2 on 2025-02-25 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_models', '0019_rename_archives_project_archive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('species_name', models.CharField(max_length=100)),
                ('species_common_name', models.CharField(max_length=100)),
                ('taxon_id', models.CharField(blank=True, max_length=100)),
                ('taxon_source', models.IntegerField(choices=[(0, 'custom'), (1, 'GBIF')], default=0)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('taxonomic_level', models.IntegerField(choices=[(0, 'species'), (1, 'genus'), (2, 'family'), (3, 'order'), (4, 'class'), (5, 'phylum'), (6, 'kingdom')], default=0)),
                ('linked_taxons', models.ManyToManyField(to='observation_editor.taxon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, editable=False, max_length=300)),
                ('obs_dt', models.DateTimeField(null=True)),
                ('source', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=1)),
                ('bounding_box', models.JSONField(blank=True, default=dict)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('lifestage', models.CharField(blank=True, max_length=15)),
                ('behavior', models.CharField(blank=True, max_length=50)),
                ('data_files', models.ManyToManyField(blank=True, related_name='observations', to='data_models.datafile')),
                ('taxon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observation_editor.taxon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
