# Generated by Django 4.2 on 2025-02-26 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observation_editor', '0002_remove_taxon_linked_taxons_taxon_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='species_common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
