# Generated by Django 4.2 on 2025-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation_editor', '0003_observation_owner_alter_taxon_species_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='observation_editor.taxon'),
        ),
    ]
