# Generated by Django 4.2 on 2025-02-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0019_rename_archives_project_archive_and_more'),
        ('observation_editor', '0004_alter_taxon_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='data_files',
            field=models.ManyToManyField(related_name='observations', to='data_models.datafile'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
