# Generated by Django 4.2 on 2025-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation_editor', '0005_alter_observation_data_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='validation_of',
            field=models.ManyToManyField(blank=True, related_name='validated_by', to='observation_editor.observation'),
        ),
        migrations.AddField(
            model_name='observation',
            name='validation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
