# Generated by Django 4.2 on 2025-03-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observation_editor', '0006_observation_validation_of_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxon',
            old_name='taxon_id',
            new_name='taxon_code',
        ),
    ]
