# Generated by Django 4.2 on 2025-03-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation_editor', '0007_rename_taxon_id_taxon_taxon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='source',
            field=models.CharField(default='human', max_length=100),
        ),
    ]
