# Generated by Django 4.2 on 2025-03-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation_editor', '0009_observation_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='confidence',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
