# Generated by Django 4.2 on 2025-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0025_alter_datafile_file_name_alter_datatype_colour_and_more'),
        ('observation_editor', '0010_alter_observation_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='data_files',
            field=models.ManyToManyField(db_index=True, related_name='observations', to='data_models.datafile'),
        ),
    ]
