# Generated by Django 4.2 on 2025-06-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation_editor', '0011_alter_observation_data_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxon',
            name='species_common_name',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='species_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
