# Generated by Django 4.2 on 2025-06-20 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_models', '0031_alter_datafile_archived_alter_datafile_file_format_and_more'),
        ('observation_editor', '0012_alter_taxon_species_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='behavior',
            field=models.CharField(blank=True, help_text='Behaviour of the observed species.', max_length=50),
        ),
        migrations.AlterField(
            model_name='observation',
            name='bounding_box',
            field=models.JSONField(default=dict, help_text="Bounding box of this observation in the format        {'x1':Left coordinate, 'y1':Bottom coordinate, 'x2': Right coordinate, 'y2': Left coordinate}."),
        ),
        migrations.AlterField(
            model_name='observation',
            name='confidence',
            field=models.FloatField(blank=True, default=None, help_text='Confidence of the observation from AI model.', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='data_files',
            field=models.ManyToManyField(db_index=True, help_text='Data files associated with the observation.', related_name='observations', to='data_models.datafile'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Extra data that the standard fields do not cover'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Numeric database ID of the observation of which this observation is a validation of.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='lifestage',
            field=models.CharField(blank=True, help_text='Lifestage of the observed species, if known.', max_length=15),
        ),
        migrations.AlterField(
            model_name='observation',
            name='number',
            field=models.IntegerField(default=1, help_text='Number of individuals in this observation, for use with whole image annotation.'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='obs_dt',
            field=models.DateTimeField(blank=True, help_text='Date and time of the observation.', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='User who created the observation.                                  Null if created by AI.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='observation',
            name='sex',
            field=models.CharField(blank=True, help_text='Sex of the observed species, if known.', max_length=10),
        ),
        migrations.AlterField(
            model_name='observation',
            name='source',
            field=models.CharField(db_index=True, default='human', help_text="Source of the observation, e.g. 'human' or an AI model name.", max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='taxon',
            field=models.ForeignKey(help_text='Taxon of the observed species.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observation_editor.taxon'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='validation_of',
            field=models.ManyToManyField(blank=True, help_text='If this observation is a validation of another observation, this field will contain the original observation(s).', related_name='validated_by', to='observation_editor.observation'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='validation_requested',
            field=models.BooleanField(default=False, help_text='If True, this observation is requested for validation by a human expert.'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='extra_data',
            field=models.JSONField(default=dict, help_text='Extra data about the taxon, e.g. avibaseID, or other relevant information.'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='id',
            field=models.BigAutoField(auto_created=True, help_text='Numeric database ID of the taxon.', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='parents',
            field=models.ManyToManyField(blank=True, help_text='Parent taxons of this taxon.', related_name='children', to='observation_editor.taxon'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='species_common_name',
            field=models.CharField(blank=True, db_index=True, help_text="Common name of the species, e.g. 'Golden Eagle'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='species_name',
            field=models.CharField(db_index=True, help_text="Scientific name of the species, e.g. 'Aquila chrysaetos'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxon_code',
            field=models.CharField(blank=True, db_index=True, help_text="Taxon code from a taxonomic database, e.g. GBIF ID,                                      or another common identifier such as 'vehicle'.", max_length=100),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxon_source',
            field=models.IntegerField(choices=[(0, 'custom'), (1, 'GBIF')], default=0, help_text='Source of the taxon code. 0 = custom, 1 = GBIF.'),
        ),
        migrations.AlterField(
            model_name='taxon',
            name='taxonomic_level',
            field=models.IntegerField(choices=[(0, 'species'), (1, 'genus'), (2, 'family'), (3, 'order'), (4, 'class'), (5, 'phylum'), (6, 'kingdom')], default=0, help_text='Taxonomic level of the species, e.g. 0 = species, 1 = genus, 2 = family, etc.'),
        ),
    ]
