# Generated by Django 4.2 on 2025-03-20 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_models', '0020_datafile_has_human'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Started'), (1, 'Unarchiving'), (2, 'Creating bundle'), (3, 'Ready'), (4, 'Failed')], default=0)),
                ('metadata_type', models.IntegerField(choices=[(0, 'base'), (1, 'Camera trap DP'), (2, 'COCO')], default=0)),
                ('includes_files', models.BooleanField(default=True)),
                ('data_files', models.ManyToManyField(related_name='data_bundles', to='data_models.datafile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
