# Generated by Django 4.2 on 2025-03-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapackage',
            name='file_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
